using FluentValidation.Results;
using MediatR;
namespace Bravo.HealthPlans.Domain.Aggregates.HealthPlansAgg.Queries.Models
{
	public partial class ConvenioQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeEqual { get; set; }
		public string NomeNotEqual { get; set; }
		public string NomeContains { get; set; }
		public string NomeStartsWith { get; set; }
		public string MatriculaEqual { get; set; }
		public string MatriculaNotEqual { get; set; }
		public string MatriculaContains { get; set; }
		public string MatriculaStartsWith { get; set; }
		public string CodigoEqual { get; set; }
		public string CodigoNotEqual { get; set; }
		public string CodigoContains { get; set; }
		public string CodigoStartsWith { get; set; }
		public string RegistroANSEqual { get; set; }
		public string RegistroANSNotEqual { get; set; }
		public string RegistroANSContains { get; set; }
		public string RegistroANSStartsWith { get; set; }
		public string CodigoReferenciaEqual { get; set; }
		public string CodigoReferenciaNotEqual { get; set; }
		public string CodigoReferenciaContains { get; set; }
		public string CodigoReferenciaStartsWith { get; set; }
		public bool? PadronizarQuantidadeDigitosEqual { get; set; }
		public int? QuantidadeDigitosEqual { get; set; }
		public int? QuantidadeDigitosSince { get; set; }
		public int? QuantidadeDigitosUntil { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class HealthPlansAggSettingsQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string UserIdEqual { get; set; }
		public string UserIdNotEqual { get; set; }
		public string UserIdContains { get; set; }
		public string UserIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class PlanoConvenioQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public int? ConvenioIdEqual { get; set; }
		public int? ConvenioIdSince { get; set; }
		public int? ConvenioIdUntil { get; set; }
		public Bravo.HealthPlans.Enumerations.ClassificacaoServicoHospitalarEnum? ClassificacaoServicoHospitalarEqual { get; set; }
		public int? TipoPlanoIdEqual { get; set; }
		public int? TipoPlanoIdSince { get; set; }
		public int? TipoPlanoIdUntil { get; set; }
		public decimal? MultiplicadorHospitalarEqual { get; set; }
		public decimal? MultiplicadorHospitalarSince { get; set; }
		public decimal? MultiplicadorHospitalarUntil { get; set; }
		public decimal? MultiplicadorProfissionalEqual { get; set; }
		public decimal? MultiplicadorProfissionalSince { get; set; }
		public decimal? MultiplicadorProfissionalUntil { get; set; }
		public decimal? MultiplicadorExameEqual { get; set; }
		public decimal? MultiplicadorExameSince { get; set; }
		public decimal? MultiplicadorExameUntil { get; set; }
		public decimal? ProcedimentoPercentualPrincipalEqual { get; set; }
		public decimal? ProcedimentoPercentualPrincipalSince { get; set; }
		public decimal? ProcedimentoPercentualPrincipalUntil { get; set; }
		public decimal? ProcedimentoPrincipalDiferenteEqual { get; set; }
		public decimal? ProcedimentoPrincipalDiferenteSince { get; set; }
		public decimal? ProcedimentoPrincipalDiferenteUntil { get; set; }
		public decimal? ProcedimentoPrincipalMesmaEqual { get; set; }
		public decimal? ProcedimentoPrincipalMesmaSince { get; set; }
		public decimal? ProcedimentoPrincipalMesmaUntil { get; set; }
		public decimal? ProcedimentoHospitalarPrincipalEqual { get; set; }
		public decimal? ProcedimentoHospitalarPrincipalSince { get; set; }
		public decimal? ProcedimentoHospitalarPrincipalUntil { get; set; }
		public decimal? ProcedimentoHospitalarDiferenteEqual { get; set; }
		public decimal? ProcedimentoHospitalarDiferenteSince { get; set; }
		public decimal? ProcedimentoHospitalarDiferenteUntil { get; set; }
		public decimal? ProcedimentoHospitalarMesmaEqual { get; set; }
		public decimal? ProcedimentoHospitalarMesmaSince { get; set; }
		public decimal? ProcedimentoHospitalarMesmaUntil { get; set; }
		public string DescricaoMedicamentoEqual { get; set; }
		public string DescricaoMedicamentoNotEqual { get; set; }
		public string DescricaoMedicamentoContains { get; set; }
		public string DescricaoMedicamentoStartsWith { get; set; }
		public string MoedaMedicamentoEqual { get; set; }
		public string MoedaMedicamentoNotEqual { get; set; }
		public string MoedaMedicamentoContains { get; set; }
		public string MoedaMedicamentoStartsWith { get; set; }
		public Bravo.HealthPlans.Enumerations.TipoTabelaEnum? TipoTabelaMedicamentoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class TipoPlanoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeEqual { get; set; }
		public string NomeNotEqual { get; set; }
		public string NomeContains { get; set; }
		public string NomeStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class ConvenioHorasEspeciaisQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string DiaEqual { get; set; }
		public string DiaNotEqual { get; set; }
		public string DiaContains { get; set; }
		public string DiaStartsWith { get; set; }
		public string HoraInicialEqual { get; set; }
		public string HoraInicialNotEqual { get; set; }
		public string HoraInicialContains { get; set; }
		public string HoraInicialStartsWith { get; set; }
		public string HoraFinalEqual { get; set; }
		public string HoraFinalNotEqual { get; set; }
		public string HoraFinalContains { get; set; }
		public string HoraFinalStartsWith { get; set; }
		public int? ConvenioIdEqual { get; set; }
		public int? ConvenioIdSince { get; set; }
		public int? ConvenioIdUntil { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.HealthPlans.Domain.Aggregates.UsersAgg.Queries.Models
{
	public partial class UserQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public string IdEqual { get; set; }
		public string IdNotEqual { get; set; }
		public string IdContains { get; set; }
		public string IdStartsWith { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
