using FluentValidation.Results;
using MediatR;
namespace Bravo.Professionals.Domain.Aggregates.CompaniesAgg.Queries.Models
{
	public partial class EmpresaQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Professionals.Domain.Aggregates.SchedulingsAgg.Queries.Models
{
	public partial class SchedulingsAggSettingsQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string UserIdEqual { get; set; }
		public string UserIdNotEqual { get; set; }
		public string UserIdContains { get; set; }
		public string UserIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class AgendaExameQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public System.DateTime? DataInicioEqual { get; set; }
		public System.DateTime? DataInicioSince { get; set; }
		public System.DateTime? DataInicioUntil { get; set; }
		public System.DateTime? DataFimEqual { get; set; }
		public System.DateTime? DataFimSince { get; set; }
		public System.DateTime? DataFimUntil { get; set; }
		public int? TempoAtendimentoEqual { get; set; }
		public int? TempoAtendimentoSince { get; set; }
		public int? TempoAtendimentoUntil { get; set; }
		public string TipoEqual { get; set; }
		public string TipoNotEqual { get; set; }
		public string TipoContains { get; set; }
		public string TipoStartsWith { get; set; }
		public string AgendaStatusEqual { get; set; }
		public string AgendaStatusNotEqual { get; set; }
		public string AgendaStatusContains { get; set; }
		public string AgendaStatusStartsWith { get; set; }
		public int? QuantidadeAgendamentosEqual { get; set; }
		public int? QuantidadeAgendamentosSince { get; set; }
		public int? QuantidadeAgendamentosUntil { get; set; }
		public int? QuantidadeEncaixesEqual { get; set; }
		public int? QuantidadeEncaixesSince { get; set; }
		public int? QuantidadeEncaixesUntil { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class AgendaSalaQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public System.DateTime? DataInicioEqual { get; set; }
		public System.DateTime? DataInicioSince { get; set; }
		public System.DateTime? DataInicioUntil { get; set; }
		public System.DateTime? DataFimEqual { get; set; }
		public System.DateTime? DataFimSince { get; set; }
		public System.DateTime? DataFimUntil { get; set; }
		public int? TempoAtendimentoEqual { get; set; }
		public int? TempoAtendimentoSince { get; set; }
		public int? TempoAtendimentoUntil { get; set; }
		public string TipoEqual { get; set; }
		public string TipoNotEqual { get; set; }
		public string TipoContains { get; set; }
		public string TipoStartsWith { get; set; }
		public string AgendaStatusEqual { get; set; }
		public string AgendaStatusNotEqual { get; set; }
		public string AgendaStatusContains { get; set; }
		public string AgendaStatusStartsWith { get; set; }
		public int? QuantidadeAgendamentosEqual { get; set; }
		public int? QuantidadeAgendamentosSince { get; set; }
		public int? QuantidadeAgendamentosUntil { get; set; }
		public int? QuantidadeEncaixesEqual { get; set; }
		public int? QuantidadeEncaixesSince { get; set; }
		public int? QuantidadeEncaixesUntil { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class FeriadoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string DescricaoEqual { get; set; }
		public string DescricaoNotEqual { get; set; }
		public string DescricaoContains { get; set; }
		public string DescricaoStartsWith { get; set; }
		public System.DateOnly? DataEqual { get; set; }
		public System.DateOnly? DataSince { get; set; }
		public System.DateOnly? DataUntil { get; set; }
		public Bravo.Schedulings.Enumerations.HolidayType? TipoEqual { get; set; }
		public string UserIdEqual { get; set; }
		public string UserIdNotEqual { get; set; }
		public string UserIdContains { get; set; }
		public string UserIdStartsWith { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class AgendaProfissionalQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string ProfissionalIdEqual { get; set; }
		public string ProfissionalIdNotEqual { get; set; }
		public string ProfissionalIdContains { get; set; }
		public string ProfissionalIdStartsWith { get; set; }
		public System.DateTime? DataInicioEqual { get; set; }
		public System.DateTime? DataInicioSince { get; set; }
		public System.DateTime? DataInicioUntil { get; set; }
		public System.DateTime? DataFimEqual { get; set; }
		public System.DateTime? DataFimSince { get; set; }
		public System.DateTime? DataFimUntil { get; set; }
		public int? TempoAtendimentoEqual { get; set; }
		public int? TempoAtendimentoSince { get; set; }
		public int? TempoAtendimentoUntil { get; set; }
		public string TipoEqual { get; set; }
		public string TipoNotEqual { get; set; }
		public string TipoContains { get; set; }
		public string TipoStartsWith { get; set; }
		public string AgendaStatusEqual { get; set; }
		public string AgendaStatusNotEqual { get; set; }
		public string AgendaStatusContains { get; set; }
		public string AgendaStatusStartsWith { get; set; }
		public int? QuantidadeAgendamentosEqual { get; set; }
		public int? QuantidadeAgendamentosSince { get; set; }
		public int? QuantidadeAgendamentosUntil { get; set; }
		public int? QuantidadeEncaixesEqual { get; set; }
		public int? QuantidadeEncaixesSince { get; set; }
		public int? QuantidadeEncaixesUntil { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Professionals.Domain.Aggregates.ProfessionalsAgg.Queries.Models
{
	public partial class ProfissionalConfiguracaoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public bool? SetorProprioEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class FuncionarioQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeEqual { get; set; }
		public string NomeNotEqual { get; set; }
		public string NomeContains { get; set; }
		public string NomeStartsWith { get; set; }
		public string NomeSocialEqual { get; set; }
		public string NomeSocialNotEqual { get; set; }
		public string NomeSocialContains { get; set; }
		public string NomeSocialStartsWith { get; set; }
		public string CPFEqual { get; set; }
		public string CPFNotEqual { get; set; }
		public string CPFContains { get; set; }
		public string CPFStartsWith { get; set; }
		public string CNPJEqual { get; set; }
		public string CNPJNotEqual { get; set; }
		public string CNPJContains { get; set; }
		public string CNPJStartsWith { get; set; }
		public string UsuarioLoginEqual { get; set; }
		public string UsuarioLoginNotEqual { get; set; }
		public string UsuarioLoginContains { get; set; }
		public string UsuarioLoginStartsWith { get; set; }
		public System.DateOnly? DataNascimentoEqual { get; set; }
		public System.DateOnly? DataNascimentoSince { get; set; }
		public System.DateOnly? DataNascimentoUntil { get; set; }
		public Bravo.Professionals.Enumerations.Enum.GeneroEnum? GeneroEqual { get; set; }
		public string EspecialidadeEqual { get; set; }
		public string EspecialidadeNotEqual { get; set; }
		public string EspecialidadeContains { get; set; }
		public string EspecialidadeStartsWith { get; set; }
		public string SubEspecialidadeEqual { get; set; }
		public string SubEspecialidadeNotEqual { get; set; }
		public string SubEspecialidadeContains { get; set; }
		public string SubEspecialidadeStartsWith { get; set; }
		public string CorpoClinicoEqual { get; set; }
		public string CorpoClinicoNotEqual { get; set; }
		public string CorpoClinicoContains { get; set; }
		public string CorpoClinicoStartsWith { get; set; }
		public string CodigoSusEqual { get; set; }
		public string CodigoSusNotEqual { get; set; }
		public string CodigoSusContains { get; set; }
		public string CodigoSusStartsWith { get; set; }
		public string CodigoCnesEqual { get; set; }
		public string CodigoCnesNotEqual { get; set; }
		public string CodigoCnesContains { get; set; }
		public string CodigoCnesStartsWith { get; set; }
		public int? CboIdEqual { get; set; }
		public int? CboIdSince { get; set; }
		public int? CboIdUntil { get; set; }
		public string ConvenioEqual { get; set; }
		public string ConvenioNotEqual { get; set; }
		public string ConvenioContains { get; set; }
		public string ConvenioStartsWith { get; set; }
		public Bravo.Professionals.Enumerations.Enum.Escolaridade? EscolaridadeEqual { get; set; }
		public string FuncaoEqual { get; set; }
		public string FuncaoNotEqual { get; set; }
		public string FuncaoContains { get; set; }
		public string FuncaoStartsWith { get; set; }
		public string CargosEqual { get; set; }
		public string CargosNotEqual { get; set; }
		public string CargosContains { get; set; }
		public string CargosStartsWith { get; set; }
		public string TelefoneEqual { get; set; }
		public string TelefoneNotEqual { get; set; }
		public string TelefoneContains { get; set; }
		public string TelefoneStartsWith { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public string IdEqual { get; set; }
		public string IdNotEqual { get; set; }
		public string IdContains { get; set; }
		public string IdStartsWith { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class ProfissionalQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeEqual { get; set; }
		public string NomeNotEqual { get; set; }
		public string NomeContains { get; set; }
		public string NomeStartsWith { get; set; }
		public string NomeSocialEqual { get; set; }
		public string NomeSocialNotEqual { get; set; }
		public string NomeSocialContains { get; set; }
		public string NomeSocialStartsWith { get; set; }
		public string CPFEqual { get; set; }
		public string CPFNotEqual { get; set; }
		public string CPFContains { get; set; }
		public string CPFStartsWith { get; set; }
		public string CNPJEqual { get; set; }
		public string CNPJNotEqual { get; set; }
		public string CNPJContains { get; set; }
		public string CNPJStartsWith { get; set; }
		public string UsuarioLoginEqual { get; set; }
		public string UsuarioLoginNotEqual { get; set; }
		public string UsuarioLoginContains { get; set; }
		public string UsuarioLoginStartsWith { get; set; }
		public System.DateOnly? DataNascimentoEqual { get; set; }
		public System.DateOnly? DataNascimentoSince { get; set; }
		public System.DateOnly? DataNascimentoUntil { get; set; }
		public Bravo.Professionals.Enumerations.Enum.GeneroEnum? GeneroEqual { get; set; }
		public string EspecialidadeEqual { get; set; }
		public string EspecialidadeNotEqual { get; set; }
		public string EspecialidadeContains { get; set; }
		public string EspecialidadeStartsWith { get; set; }
		public string SubEspecialidadeEqual { get; set; }
		public string SubEspecialidadeNotEqual { get; set; }
		public string SubEspecialidadeContains { get; set; }
		public string SubEspecialidadeStartsWith { get; set; }
		public string CorpoClinicoEqual { get; set; }
		public string CorpoClinicoNotEqual { get; set; }
		public string CorpoClinicoContains { get; set; }
		public string CorpoClinicoStartsWith { get; set; }
		public string CodigoSusEqual { get; set; }
		public string CodigoSusNotEqual { get; set; }
		public string CodigoSusContains { get; set; }
		public string CodigoSusStartsWith { get; set; }
		public string CodigoCnesEqual { get; set; }
		public string CodigoCnesNotEqual { get; set; }
		public string CodigoCnesContains { get; set; }
		public string CodigoCnesStartsWith { get; set; }
		public int? CboIdEqual { get; set; }
		public int? CboIdSince { get; set; }
		public int? CboIdUntil { get; set; }
		public string ConvenioEqual { get; set; }
		public string ConvenioNotEqual { get; set; }
		public string ConvenioContains { get; set; }
		public string ConvenioStartsWith { get; set; }
		public Bravo.Professionals.Enumerations.Enum.Escolaridade? EscolaridadeEqual { get; set; }
		public string FuncaoEqual { get; set; }
		public string FuncaoNotEqual { get; set; }
		public string FuncaoContains { get; set; }
		public string FuncaoStartsWith { get; set; }
		public string CargosEqual { get; set; }
		public string CargosNotEqual { get; set; }
		public string CargosContains { get; set; }
		public string CargosStartsWith { get; set; }
		public string TelefoneEqual { get; set; }
		public string TelefoneNotEqual { get; set; }
		public string TelefoneContains { get; set; }
		public string TelefoneStartsWith { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public string IdEqual { get; set; }
		public string IdNotEqual { get; set; }
		public string IdContains { get; set; }
		public string IdStartsWith { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class ProfessionalsAggSettingsQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string UserIdEqual { get; set; }
		public string UserIdNotEqual { get; set; }
		public string UserIdContains { get; set; }
		public string UserIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class CboQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string CodigoEqual { get; set; }
		public string CodigoNotEqual { get; set; }
		public string CodigoContains { get; set; }
		public string CodigoStartsWith { get; set; }
		public string TitulosEqual { get; set; }
		public string TitulosNotEqual { get; set; }
		public string TitulosContains { get; set; }
		public string TitulosStartsWith { get; set; }
		public string TipoEqual { get; set; }
		public string TipoNotEqual { get; set; }
		public string TipoContains { get; set; }
		public string TipoStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Professionals.Domain.Aggregates.UsersAgg.Queries.Models
{
	public partial class UserQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public string IdEqual { get; set; }
		public string IdNotEqual { get; set; }
		public string IdContains { get; set; }
		public string IdStartsWith { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
