using FluentValidation.Results;
using MediatR;
namespace Bravo.Companies.Domain.Aggregates.CompaniesAgg.Queries.Models
{
	public partial class EmpresaConfiguracaoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public bool? SetorProprioEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class EmpresaQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public int? GrupoEmpresaIdEqual { get; set; }
		public int? GrupoEmpresaIdSince { get; set; }
		public int? GrupoEmpresaIdUntil { get; set; }
		public bool? IsFilialEqual { get; set; }
		public string CNESEqual { get; set; }
		public string CNESNotEqual { get; set; }
		public string CNESContains { get; set; }
		public string CNESStartsWith { get; set; }
		public string ANSEqual { get; set; }
		public string ANSNotEqual { get; set; }
		public string ANSContains { get; set; }
		public string ANSStartsWith { get; set; }
		public string CodigoSUSEqual { get; set; }
		public string CodigoSUSNotEqual { get; set; }
		public string CodigoSUSContains { get; set; }
		public string CodigoSUSStartsWith { get; set; }
		public bool? TerceirizadoEqual { get; set; }
		public string CNPJEqual { get; set; }
		public string CNPJNotEqual { get; set; }
		public string CNPJContains { get; set; }
		public string CNPJStartsWith { get; set; }
		public string RazaoSocialEqual { get; set; }
		public string RazaoSocialNotEqual { get; set; }
		public string RazaoSocialContains { get; set; }
		public string RazaoSocialStartsWith { get; set; }
		public string NomeFantasiaEqual { get; set; }
		public string NomeFantasiaNotEqual { get; set; }
		public string NomeFantasiaContains { get; set; }
		public string NomeFantasiaStartsWith { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public Bravo.Companies.Enumerations.InstituicaoType? InstituicaoTypeEqual { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class GrupoEmpresaContactsQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string EmailEqual { get; set; }
		public string EmailNotEqual { get; set; }
		public string EmailContains { get; set; }
		public string EmailStartsWith { get; set; }
		public string TelefoneEqual { get; set; }
		public string TelefoneNotEqual { get; set; }
		public string TelefoneContains { get; set; }
		public string TelefoneStartsWith { get; set; }
		public string TipoTelefoneEqual { get; set; }
		public string TipoTelefoneNotEqual { get; set; }
		public string TipoTelefoneContains { get; set; }
		public string TipoTelefoneStartsWith { get; set; }
		public string WebSiteEqual { get; set; }
		public string WebSiteNotEqual { get; set; }
		public string WebSiteContains { get; set; }
		public string WebSiteStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class GrupoEmpresaConfiguracaoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public bool? SetorProprioEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class CompaniesAggSettingsQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string UserIdEqual { get; set; }
		public string UserIdNotEqual { get; set; }
		public string UserIdContains { get; set; }
		public string UserIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class GrupoEmpresaEnderecoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public int? GrupoEmpresaIdEqual { get; set; }
		public int? GrupoEmpresaIdSince { get; set; }
		public int? GrupoEmpresaIdUntil { get; set; }
		public int? EnderecoIdEqual { get; set; }
		public int? EnderecoIdSince { get; set; }
		public int? EnderecoIdUntil { get; set; }
		public string NumeroEqual { get; set; }
		public string NumeroNotEqual { get; set; }
		public string NumeroContains { get; set; }
		public string NumeroStartsWith { get; set; }
		public string ReferenciaEqual { get; set; }
		public string ReferenciaNotEqual { get; set; }
		public string ReferenciaContains { get; set; }
		public string ReferenciaStartsWith { get; set; }
		public string TipoEnderecoEqual { get; set; }
		public string TipoEnderecoNotEqual { get; set; }
		public string TipoEnderecoContains { get; set; }
		public string TipoEnderecoStartsWith { get; set; }
		public string ComplementoEqual { get; set; }
		public string ComplementoNotEqual { get; set; }
		public string ComplementoContains { get; set; }
		public string ComplementoStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class GrupoEmpresaQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string CNPJEqual { get; set; }
		public string CNPJNotEqual { get; set; }
		public string CNPJContains { get; set; }
		public string CNPJStartsWith { get; set; }
		public string RazaoSocialEqual { get; set; }
		public string RazaoSocialNotEqual { get; set; }
		public string RazaoSocialContains { get; set; }
		public string RazaoSocialStartsWith { get; set; }
		public string NomeFantasiaEqual { get; set; }
		public string NomeFantasiaNotEqual { get; set; }
		public string NomeFantasiaContains { get; set; }
		public string NomeFantasiaStartsWith { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public Bravo.Companies.Enumerations.InstituicaoType? InstituicaoTypeEqual { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class EmpresaEnderecoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public int? EnderecoIdEqual { get; set; }
		public int? EnderecoIdSince { get; set; }
		public int? EnderecoIdUntil { get; set; }
		public string NumeroEqual { get; set; }
		public string NumeroNotEqual { get; set; }
		public string NumeroContains { get; set; }
		public string NumeroStartsWith { get; set; }
		public string ReferenciaEqual { get; set; }
		public string ReferenciaNotEqual { get; set; }
		public string ReferenciaContains { get; set; }
		public string ReferenciaStartsWith { get; set; }
		public string TipoEnderecoEqual { get; set; }
		public string TipoEnderecoNotEqual { get; set; }
		public string TipoEnderecoContains { get; set; }
		public string TipoEnderecoStartsWith { get; set; }
		public string ComplementoEqual { get; set; }
		public string ComplementoNotEqual { get; set; }
		public string ComplementoContains { get; set; }
		public string ComplementoStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class EmpresaContactsQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string EmailEqual { get; set; }
		public string EmailNotEqual { get; set; }
		public string EmailContains { get; set; }
		public string EmailStartsWith { get; set; }
		public string TelefoneEqual { get; set; }
		public string TelefoneNotEqual { get; set; }
		public string TelefoneContains { get; set; }
		public string TelefoneStartsWith { get; set; }
		public string TipoTelefoneEqual { get; set; }
		public string TipoTelefoneNotEqual { get; set; }
		public string TipoTelefoneContains { get; set; }
		public string TipoTelefoneStartsWith { get; set; }
		public string WebSiteEqual { get; set; }
		public string WebSiteNotEqual { get; set; }
		public string WebSiteContains { get; set; }
		public string WebSiteStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Companies.Domain.Aggregates.ProfessionalsAgg.Queries.Models
{
	public partial class ProfissionalConfiguracaoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public bool? SetorProprioEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class FuncionarioQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeEqual { get; set; }
		public string NomeNotEqual { get; set; }
		public string NomeContains { get; set; }
		public string NomeStartsWith { get; set; }
		public string NomeSocialEqual { get; set; }
		public string NomeSocialNotEqual { get; set; }
		public string NomeSocialContains { get; set; }
		public string NomeSocialStartsWith { get; set; }
		public string CPFEqual { get; set; }
		public string CPFNotEqual { get; set; }
		public string CPFContains { get; set; }
		public string CPFStartsWith { get; set; }
		public string CNPJEqual { get; set; }
		public string CNPJNotEqual { get; set; }
		public string CNPJContains { get; set; }
		public string CNPJStartsWith { get; set; }
		public string UsuarioLoginEqual { get; set; }
		public string UsuarioLoginNotEqual { get; set; }
		public string UsuarioLoginContains { get; set; }
		public string UsuarioLoginStartsWith { get; set; }
		public System.DateOnly? DataNascimentoEqual { get; set; }
		public System.DateOnly? DataNascimentoSince { get; set; }
		public System.DateOnly? DataNascimentoUntil { get; set; }
		public Bravo.Professionals.Enumerations.Enum.GeneroEnum? GeneroEqual { get; set; }
		public string EspecialidadeEqual { get; set; }
		public string EspecialidadeNotEqual { get; set; }
		public string EspecialidadeContains { get; set; }
		public string EspecialidadeStartsWith { get; set; }
		public string SubEspecialidadeEqual { get; set; }
		public string SubEspecialidadeNotEqual { get; set; }
		public string SubEspecialidadeContains { get; set; }
		public string SubEspecialidadeStartsWith { get; set; }
		public string CorpoClinicoEqual { get; set; }
		public string CorpoClinicoNotEqual { get; set; }
		public string CorpoClinicoContains { get; set; }
		public string CorpoClinicoStartsWith { get; set; }
		public string CodigoSusEqual { get; set; }
		public string CodigoSusNotEqual { get; set; }
		public string CodigoSusContains { get; set; }
		public string CodigoSusStartsWith { get; set; }
		public string CodigoCnesEqual { get; set; }
		public string CodigoCnesNotEqual { get; set; }
		public string CodigoCnesContains { get; set; }
		public string CodigoCnesStartsWith { get; set; }
		public int? CboIdEqual { get; set; }
		public int? CboIdSince { get; set; }
		public int? CboIdUntil { get; set; }
		public string ConvenioEqual { get; set; }
		public string ConvenioNotEqual { get; set; }
		public string ConvenioContains { get; set; }
		public string ConvenioStartsWith { get; set; }
		public Bravo.Professionals.Enumerations.Enum.Escolaridade? EscolaridadeEqual { get; set; }
		public string FuncaoEqual { get; set; }
		public string FuncaoNotEqual { get; set; }
		public string FuncaoContains { get; set; }
		public string FuncaoStartsWith { get; set; }
		public string CargosEqual { get; set; }
		public string CargosNotEqual { get; set; }
		public string CargosContains { get; set; }
		public string CargosStartsWith { get; set; }
		public string TelefoneEqual { get; set; }
		public string TelefoneNotEqual { get; set; }
		public string TelefoneContains { get; set; }
		public string TelefoneStartsWith { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public string IdEqual { get; set; }
		public string IdNotEqual { get; set; }
		public string IdContains { get; set; }
		public string IdStartsWith { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class ProfissionalQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeEqual { get; set; }
		public string NomeNotEqual { get; set; }
		public string NomeContains { get; set; }
		public string NomeStartsWith { get; set; }
		public string NomeSocialEqual { get; set; }
		public string NomeSocialNotEqual { get; set; }
		public string NomeSocialContains { get; set; }
		public string NomeSocialStartsWith { get; set; }
		public string CPFEqual { get; set; }
		public string CPFNotEqual { get; set; }
		public string CPFContains { get; set; }
		public string CPFStartsWith { get; set; }
		public string CNPJEqual { get; set; }
		public string CNPJNotEqual { get; set; }
		public string CNPJContains { get; set; }
		public string CNPJStartsWith { get; set; }
		public string UsuarioLoginEqual { get; set; }
		public string UsuarioLoginNotEqual { get; set; }
		public string UsuarioLoginContains { get; set; }
		public string UsuarioLoginStartsWith { get; set; }
		public System.DateOnly? DataNascimentoEqual { get; set; }
		public System.DateOnly? DataNascimentoSince { get; set; }
		public System.DateOnly? DataNascimentoUntil { get; set; }
		public Bravo.Professionals.Enumerations.Enum.GeneroEnum? GeneroEqual { get; set; }
		public string EspecialidadeEqual { get; set; }
		public string EspecialidadeNotEqual { get; set; }
		public string EspecialidadeContains { get; set; }
		public string EspecialidadeStartsWith { get; set; }
		public string SubEspecialidadeEqual { get; set; }
		public string SubEspecialidadeNotEqual { get; set; }
		public string SubEspecialidadeContains { get; set; }
		public string SubEspecialidadeStartsWith { get; set; }
		public string CorpoClinicoEqual { get; set; }
		public string CorpoClinicoNotEqual { get; set; }
		public string CorpoClinicoContains { get; set; }
		public string CorpoClinicoStartsWith { get; set; }
		public string CodigoSusEqual { get; set; }
		public string CodigoSusNotEqual { get; set; }
		public string CodigoSusContains { get; set; }
		public string CodigoSusStartsWith { get; set; }
		public string CodigoCnesEqual { get; set; }
		public string CodigoCnesNotEqual { get; set; }
		public string CodigoCnesContains { get; set; }
		public string CodigoCnesStartsWith { get; set; }
		public int? CboIdEqual { get; set; }
		public int? CboIdSince { get; set; }
		public int? CboIdUntil { get; set; }
		public string ConvenioEqual { get; set; }
		public string ConvenioNotEqual { get; set; }
		public string ConvenioContains { get; set; }
		public string ConvenioStartsWith { get; set; }
		public Bravo.Professionals.Enumerations.Enum.Escolaridade? EscolaridadeEqual { get; set; }
		public string FuncaoEqual { get; set; }
		public string FuncaoNotEqual { get; set; }
		public string FuncaoContains { get; set; }
		public string FuncaoStartsWith { get; set; }
		public string CargosEqual { get; set; }
		public string CargosNotEqual { get; set; }
		public string CargosContains { get; set; }
		public string CargosStartsWith { get; set; }
		public string TelefoneEqual { get; set; }
		public string TelefoneNotEqual { get; set; }
		public string TelefoneContains { get; set; }
		public string TelefoneStartsWith { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public string IdEqual { get; set; }
		public string IdNotEqual { get; set; }
		public string IdContains { get; set; }
		public string IdStartsWith { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class CboQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string CodigoEqual { get; set; }
		public string CodigoNotEqual { get; set; }
		public string CodigoContains { get; set; }
		public string CodigoStartsWith { get; set; }
		public string TitulosEqual { get; set; }
		public string TitulosNotEqual { get; set; }
		public string TitulosContains { get; set; }
		public string TitulosStartsWith { get; set; }
		public string TipoEqual { get; set; }
		public string TipoNotEqual { get; set; }
		public string TipoContains { get; set; }
		public string TipoStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Companies.Domain.Aggregates.PatientsAgg.Queries.Models
{
	public partial class PacienteQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeEqual { get; set; }
		public string NomeNotEqual { get; set; }
		public string NomeContains { get; set; }
		public string NomeStartsWith { get; set; }
		public string CpfEqual { get; set; }
		public string CpfNotEqual { get; set; }
		public string CpfContains { get; set; }
		public string CpfStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Companies.Domain.Aggregates.SchedulingsAgg.Queries.Models
{
	public partial class AgendaExameQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public System.DateTime? DataInicioEqual { get; set; }
		public System.DateTime? DataInicioSince { get; set; }
		public System.DateTime? DataInicioUntil { get; set; }
		public System.DateTime? DataFimEqual { get; set; }
		public System.DateTime? DataFimSince { get; set; }
		public System.DateTime? DataFimUntil { get; set; }
		public int? TempoAtendimentoEqual { get; set; }
		public int? TempoAtendimentoSince { get; set; }
		public int? TempoAtendimentoUntil { get; set; }
		public string TipoEqual { get; set; }
		public string TipoNotEqual { get; set; }
		public string TipoContains { get; set; }
		public string TipoStartsWith { get; set; }
		public string ScheduleStatusEqual { get; set; }
		public string ScheduleStatusNotEqual { get; set; }
		public string ScheduleStatusContains { get; set; }
		public string ScheduleStatusStartsWith { get; set; }
		public int? QuantidadeAgendamentosEqual { get; set; }
		public int? QuantidadeAgendamentosSince { get; set; }
		public int? QuantidadeAgendamentosUntil { get; set; }
		public int? QuantidadeEncaixesEqual { get; set; }
		public int? QuantidadeEncaixesSince { get; set; }
		public int? QuantidadeEncaixesUntil { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class FeriadoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string DescricaoEqual { get; set; }
		public string DescricaoNotEqual { get; set; }
		public string DescricaoContains { get; set; }
		public string DescricaoStartsWith { get; set; }
		public System.DateOnly? DataEqual { get; set; }
		public System.DateOnly? DataSince { get; set; }
		public System.DateOnly? DataUntil { get; set; }
		public Bravo.Schedulings.Enumerations.HolidayType? TipoEqual { get; set; }
		public string UserIdEqual { get; set; }
		public string UserIdNotEqual { get; set; }
		public string UserIdContains { get; set; }
		public string UserIdStartsWith { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class AgendaProfissionalQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeProfissionalEqual { get; set; }
		public string NomeProfissionalNotEqual { get; set; }
		public string NomeProfissionalContains { get; set; }
		public string NomeProfissionalStartsWith { get; set; }
		public string ConselhoEqual { get; set; }
		public string ConselhoNotEqual { get; set; }
		public string ConselhoContains { get; set; }
		public string ConselhoStartsWith { get; set; }
		public string CBOProfissionalEqual { get; set; }
		public string CBOProfissionalNotEqual { get; set; }
		public string CBOProfissionalContains { get; set; }
		public string CBOProfissionalStartsWith { get; set; }
		public string DuracaoConsultaEqual { get; set; }
		public string DuracaoConsultaNotEqual { get; set; }
		public string DuracaoConsultaContains { get; set; }
		public string DuracaoConsultaStartsWith { get; set; }
		public string CotaAtendimentoEqual { get; set; }
		public string CotaAtendimentoNotEqual { get; set; }
		public string CotaAtendimentoContains { get; set; }
		public string CotaAtendimentoStartsWith { get; set; }
		public System.DateTime? DataInicioEqual { get; set; }
		public System.DateTime? DataInicioSince { get; set; }
		public System.DateTime? DataInicioUntil { get; set; }
		public System.DateTime? DataFimEqual { get; set; }
		public System.DateTime? DataFimSince { get; set; }
		public System.DateTime? DataFimUntil { get; set; }
		public int? TempoAtendimentoEqual { get; set; }
		public int? TempoAtendimentoSince { get; set; }
		public int? TempoAtendimentoUntil { get; set; }
		public string TipoEqual { get; set; }
		public string TipoNotEqual { get; set; }
		public string TipoContains { get; set; }
		public string TipoStartsWith { get; set; }
		public string ScheduleStatusEqual { get; set; }
		public string ScheduleStatusNotEqual { get; set; }
		public string ScheduleStatusContains { get; set; }
		public string ScheduleStatusStartsWith { get; set; }
		public int? QuantidadeAgendamentosEqual { get; set; }
		public int? QuantidadeAgendamentosSince { get; set; }
		public int? QuantidadeAgendamentosUntil { get; set; }
		public int? QuantidadeEncaixesEqual { get; set; }
		public int? QuantidadeEncaixesSince { get; set; }
		public int? QuantidadeEncaixesUntil { get; set; }
		public bool? AtivoEqual { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Companies.Domain.Aggregates.HealthPlansAgg.Queries.Models
{
	public partial class ConvenioQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string NomeEqual { get; set; }
		public string NomeNotEqual { get; set; }
		public string NomeContains { get; set; }
		public string NomeStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Companies.Domain.Aggregates.ClinicalProceduresAgg.Queries.Models
{
	public partial class ProcedimentoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public int? CodigoProcedimentoEqual { get; set; }
		public int? CodigoProcedimentoSince { get; set; }
		public int? CodigoProcedimentoUntil { get; set; }
		public int? DescricaoEqual { get; set; }
		public int? DescricaoSince { get; set; }
		public int? DescricaoUntil { get; set; }
		public string OrientacaoEqual { get; set; }
		public string OrientacaoNotEqual { get; set; }
		public string OrientacaoContains { get; set; }
		public string OrientacaoStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Companies.Domain.Aggregates.UsersAgg.Queries.Models
{
	public partial class UserQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string UserNameEqual { get; set; }
		public string UserNameNotEqual { get; set; }
		public string UserNameContains { get; set; }
		public string UserNameStartsWith { get; set; }
		public string NameEqual { get; set; }
		public string NameNotEqual { get; set; }
		public string NameContains { get; set; }
		public string NameStartsWith { get; set; }
		public string EmailEqual { get; set; }
		public string EmailNotEqual { get; set; }
		public string EmailContains { get; set; }
		public string EmailStartsWith { get; set; }
		public int? EmpresaIdEqual { get; set; }
		public int? EmpresaIdSince { get; set; }
		public int? EmpresaIdUntil { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public string IdEqual { get; set; }
		public string IdNotEqual { get; set; }
		public string IdContains { get; set; }
		public string IdStartsWith { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Companies.Domain.Aggregates.PartnersAgg.Queries.Models
{
	public partial class FornecedorQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class PublicitarioQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
namespace Bravo.Companies.Domain.Aggregates.AddressesAgg.Queries.Models
{
	public partial class EnderecoQueryModel {
		public string Selector { get; set; }
		public string OrderBy { get; set; }
		public bool? OrderByDesc { get; set; }
		public bool? GetOnlySummary { get; set; }
		public IRequest<ValidationResult> Command { get; set; }
		public string CEPEqual { get; set; }
		public string CEPNotEqual { get; set; }
		public string CEPContains { get; set; }
		public string CEPStartsWith { get; set; }
		public string LogradouroEqual { get; set; }
		public string LogradouroNotEqual { get; set; }
		public string LogradouroContains { get; set; }
		public string LogradouroStartsWith { get; set; }
		public string Bairro_DistritoEqual { get; set; }
		public string Bairro_DistritoNotEqual { get; set; }
		public string Bairro_DistritoContains { get; set; }
		public string Bairro_DistritoStartsWith { get; set; }
		public string Cidade_LocalidadeEqual { get; set; }
		public string Cidade_LocalidadeNotEqual { get; set; }
		public string Cidade_LocalidadeContains { get; set; }
		public string Cidade_LocalidadeStartsWith { get; set; }
		public string UFEqual { get; set; }
		public string UFNotEqual { get; set; }
		public string UFContains { get; set; }
		public string UFStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public int? IdEqual { get; set; }
		public string ExternalIdEqual { get; set; }
		public string ExternalIdNotEqual { get; set; }
		public string ExternalIdContains { get; set; }
		public string ExternalIdStartsWith { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
